name: build-action

on:
    pull_request:
        branches:
            - main
        paths:
            - "**"
            - "!**.md"
    push:
        branches:
            - main
        paths:
            - "**"
            - "!**.md"
    release:
        types:
            - created
    workflow_call:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
                with:
                    submodules: true
            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    distribution: 'temurin'
                    cache: 'gradle'
                    java-version: 17
            -   name: Set up Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: 18
            -   uses: pnpm/action-setup@v2.2.4
                name: Install pnpm
                id: pnpm-install
                with:
                    version: 8
                    run_install: false
            -   name: Get pnpm store directory
                id: pnpm-cache
                run: |
                    echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
            -   uses: actions/cache@v3
                name: Setup pnpm cache
                with:
                    path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
                    key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/console/pnpm-lock.yaml') }}
                    restore-keys: |
                        ${{ runner.os }}-pnpm-store-
            -   name: Grant execute permission for gradlew
                run: chmod +x ./gradlew
            -   name: Install Frontend Dependencies
                run: ./gradlew pnpmInstall
            -   name: Build with Gradle
                run: |
                    # Set the version with tag name when releasing
                    version=${{ github.event.release.tag_name }}
                    version=${version#v}
                    sed -i "s/version=.*-SNAPSHOT$/version=$version/1" gradle.properties
                    ./gradlew clean build -x test
            -   name: Archive plugin-lucence-for-halo jar
                uses: actions/upload-artifact@v3
                with:
                    name: plugin-lucence-for-halo
                    path: |
                        build/libs/*.jar
                    retention-days: 3